### ISSUE TITLE
Design for Mobile NavBar

### ISSUE THREAD

**Issue by ajohns619** [JumboCode/E4P#146]
The navigation bar on mobile is currently too large for the page and looks disorganized. We need to update the mobile designs to accommodate a navigation bar with "Help", "Feedback", and "Login" options. These should be collapsible so that most of the time they are not shown, only the E4P logo and a button to expand the options.

**Comment by titapapunne** [comment]
![navbar](https://user-images.githubusercontent.com/43229649/52924267-08102780-32fa-11e9-84ed-05d9a7611ca5.jpg)
