### ISSUE TITLE
Desings for Chat Updates

### ISSUE THREAD

**Issue by ajohns619** [JumboCode/E4P#149]
E4P wants a user to not just land on an empty (and intimidating) chat system. Instead they would like a message saying that an ear has picked up and is ready to respond, and all they need to do is to type a message. Similarly, the admin page should have messages updating when a user has left etc. Both of these could be implemented by having a message like the ones messenger displays when you add/remove someone from a group chat.

**Comment by ajohns619** [comment]
From E4P: "It would be nice if there were a message indicating that the user has disconnected"

**Comment by titapapunne** [comment]
<img width="591" alt="the user has disconnected" src="https://user-images.githubusercontent.com/43229649/52924767-18290680-32fc-11e9-98a7-abbaa2fd62ae.png">

<img width="645" alt="user mobile" src="https://user-images.githubusercontent.com/43229649/52925177-e5800d80-32fd-11e9-85e9-770b9ecc7839.png">
