### ISSUE TITLE
Read Receipts on Index and Admin Page

### ISSUE THREAD

**Issue by ajohns619** [JumboCode/E4P#150]
https://github.com/JumboCode/E4P/issues/64 is working on time stamps, we'd also like read-receipts. This could be a little check next to the message. This task involves both the front end chat component to detect and display these reads, as well as the socket routing to send the reads to the other side. The front end component should be handled within chat.js and chat.css, the socket.io infrastructure will likely resemble the "typing"/"stop typing" messages.

**Comment by ajohns619** [comment]
E4P want read receipts only on the Ears' side: "Ears will respond to every message so read receipts won't really help the caller"

**Comment by JamaicanMoose** [comment]
need to update wiki with new client side objects & sockets
