### ISSUE TITLE
Color Changes for Chat Notifications

### ISSUE THREAD

**Issue by titapapunne** [JumboCode/E4P#177]
E4P finds the color difference between chat boxes (new notification vs no new notification) confusing. Change colors so that the chat boxes with new notifications have darker background color than chats without new notifications.

**Comment by titapapunne** [comment]
<img width="870" alt="login help page and notification" src="https://user-images.githubusercontent.com/43229649/52925868-3e04da00-3301-11e9-99d1-0272883b2b2c.png">

<img width="810" alt="accept new chat" src="https://user-images.githubusercontent.com/43229649/52925937-a0f67100-3301-11e9-99b9-1d521d3ea0bf.png">

**Comment by ajohns619** [comment]
Merged into Master: https://github.com/JumboCode/E4P/commit/1885b485c36db8d290b1219c307412969e31108c
