### ISSUE TITLE
Backend Authentication

### ISSUE THREAD

**Issue by ajohns619** [JumboCode/E4P#2]
Add Authentication capabilities to backend server file with Passport. This will need to handle logins, logouts, and registrations. Users will have to be stored in a database. Docs: http://www.passportjs.org/docs/

**Comment by scmeggitt** [comment]
How to add Passport:
- create an Admin Schema (admin.js)
- need a login form (passport.js)
---- input username and password
---- check username in db
---- check password is valid
---- redirect to admin page 
- create logout path
- determine how to register admins and what data needs to be stored

**Comment by ajohns619** [comment]
Still needs to be done:
- Add an admin model (to be used in server.js on line 26)
- Add the login, logout, and register routes, that use the same admin model
Check out this solution to see an example: https://github.com/JumboCode/BINJ/blob/master/controllers/accountController.js
