### ISSUE TITLE
Switch User DB to MongoDB

### ISSUE THREAD

**Issue by ajohns619** [JumboCode/E4P#257]
Because herokuapp resets and pulls from the repo every 24 hours, we can't use sqlite in the folder structure. So we need to replace the sqlite db to a mongo db that we can host on a persistent service.

**Comment by JamaicanMoose** [comment]
Alternatively we could remove the sqlite file from the git repo and pass it to the server as an environment variable.

**Comment by JamaicanMoose** [comment]
Pr should fix this issue #245

**Comment by ajohns619** [comment]
How would we pass in the sqlite file? Sqlite usually just has a file in the folder, so we need to change to a service where the db can run in its own separate process (that we might link through an env var). As far as I understand, sqlite doesn't allow us to do that, so the only options are changing to either mongodb, or postgresql. In my mind mongodb will be easiest, since our tables are fairly simple. Heroku has an article about this here: https://devcenter.heroku.com/articles/sqlite3#disk-backed-storage

**Comment by JamaicanMoose** [comment]
Makes sense, I retract my previous suggestion

**Comment by ajohns619** [comment]
Switched from Mongodb to PostgreSQL
