### ISSUE TITLE
Proportins and Sizing

### ISSUE THREAD

**Issue by ajohns619** [JumboCode/E4P#48]
Create designs for proportions, sizing, and fonts.

**Comment by isabelwhittakerwalker** [comment]
<img width="760" alt="screen shot 2018-11-12 at 8 35 53 pm" src="https://user-images.githubusercontent.com/43223712/48384982-b03ea080-e6ba-11e8-9aa5-9104b23450ee.png">

**Comment by isabelwhittakerwalker** [comment]
<img width="487" alt="screen shot 2018-11-18 at 9 49 52 pm" src="https://user-images.githubusercontent.com/43223712/48683588-f5137d00-eb7b-11e8-8536-f967fde8868a.png">
<img width="700" alt="screen shot 2018-11-18 at 9 49 36 pm" src="https://user-images.githubusercontent.com/43223712/48683591-f80e6d80-eb7b-11e8-8f95-5a61f1c16827.png">

**Comment by isabelwhittakerwalker** [comment]
<img width="490" alt="screen shot 2018-11-20 at 8 02 28 pm" src="https://user-images.githubusercontent.com/43223712/48812237-75162000-ecff-11e8-83a3-7e001b50c0d9.png">
<img width="498" alt="screen shot 2018-11-20 at 8 02 20 pm" src="https://user-images.githubusercontent.com/43223712/48812239-79423d80-ecff-11e8-8eb2-06947e5fb94d.png">
