### ISSUE TITLE
Design Mockup

### ISSUE THREAD

**Issue by ajohns619** [JumboCode/E4P#6]
We should have design mockups for both frontends.

**Comment by isabelwhittakerwalker** [comment]
Wireframes for Admin Desktop: 
[E4PAdminDesktop.pdf](https://github.com/JumboCode/E4P/files/2465499/E4PAdminDesktop.pdf)
Still needs to be refined for font sizing, and to make compatible with different screen sizes.

**Comment by isabelwhittakerwalker** [comment]
User Desktop Pages: 
<img width="675" alt="screen shot 2018-10-14 at 6 34 18 pm" src="https://user-images.githubusercontent.com/43223712/46923021-cdab1c80-cfdf-11e8-8049-92c6b03607fc.png">
<img width="671" alt="screen shot 2018-10-14 at 6 34 12 pm" src="https://user-images.githubusercontent.com/43223712/46923022-cedc4980-cfdf-11e8-90f7-3ce61e4e1b9d.png">

**Comment by isabelwhittakerwalker** [comment]
<img width="661" alt="screen shot 2018-10-14 at 9 57 13 pm" src="https://user-images.githubusercontent.com/43223712/46925837-2be5f880-cffc-11e8-866e-e9440ae57766.png">
<img width="811" alt="screen shot 2018-10-14 at 9 56 45 pm" src="https://user-images.githubusercontent.com/43223712/46925839-2dafbc00-cffc-11e8-8a65-9a2d1f6df9ce.png">
<img width="894" alt="screen shot 2018-10-14 at 9 56 19 pm" src="https://user-images.githubusercontent.com/43223712/46925840-2f797f80-cffc-11e8-99bd-9386cf91162f.png">

**Comment by isabelwhittakerwalker** [comment]
New users mobile

<img width="669" alt="screen shot 2018-10-17 at 12 45 25 pm" src="https://user-images.githubusercontent.com/43223712/47102382-9a98a100-d20a-11e8-87e8-7d6abb5467ab.png">

**Comment by isabelwhittakerwalker** [comment]
New User desktop
<img width="896" alt="screen shot 2018-10-17 at 12 46 32 pm" src="https://user-images.githubusercontent.com/43223712/47102415-b603ac00-d20a-11e8-9bed-115182d0263c.png">

**Comment by isabelwhittakerwalker** [comment]
<img width="640" alt="screen shot 2018-10-21 at 4 26 45 pm" src="https://user-images.githubusercontent.com/43223712/47272084-53821700-d54e-11e8-9a83-5d59e1a88db0.png">
<img width="394" alt="screen shot 2018-10-21 at 4 27 05 pm" src="https://user-images.githubusercontent.com/43223712/47272085-54b34400-d54e-11e8-91ce-60e95509f24b.png">
<img width="549" alt="screen shot 2018-10-21 at 4 27 10 pm" src="https://user-images.githubusercontent.com/43223712/47272087-55e47100-d54e-11e8-852e-db4bcc9fafd4.png">
<img width="198" alt="screen shot 2018-10-21 at 4 27 16 pm" src="https://user-images.githubusercontent.com/43223712/47272090-57159e00-d54e-11e8-8b12-858322643ee4.png">

**Comment by isabelwhittakerwalker** [comment]
<img width="575" alt="screen shot 2018-10-21 at 4 29 30 pm" src="https://user-images.githubusercontent.com/43223712/47272108-a22fb100-d54e-11e8-802d-18fb6e7bc92c.png">

**Comment by ajohns619** [comment]
Complete Mockups can be found here: https://github.com/JumboCode/E4P/wiki/Design.
